name: Push

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x.x

      - name: Test Satori.Protocol
        run: dotnet test tests/Satori.Protocol.Tests/

  nuget-publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x.x

      - name: Publish Satori.Protocol
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/Satori.Protocol/Satori.Protocol.csproj
          VERSION_FILE_PATH: Directory.Build.props
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: Publish Satori.Client
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/Satori.Client/Satori.Client.csproj
          VERSION_FILE_PATH: Directory.Build.props
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}