name: Test and Publish

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x.x

      - name: Test Satori.Protocol
        run: dotnet test tests/Satori.Protocol.Tests/


  publish:
    name: Publish NuGet Packages
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x.x

      - name: Publish Satori.Protocol
        id: publish-core
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/Satori.Protocol/Satori.Protocol.csproj
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: Publish Satori.Client
        id: publish-core
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: src/Satori.Client/Satori.Client.csproj
          TAG_COMMIT: false
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}